name: Export Vercel Envs to GitHub Actions
description: Export Vercel Envs to GitHub Actions

inputs:
  project-id:
    description: 'Vercel Project ID'
    required: true
  token:
    description: 'Vercel Token'
    required: true
  target:
    description: 'Target environemnt (production, preview, development). Default is production.'
    required: false
    default: 'production'

runs:
  using: node20
  main: dist/index.js
