name: Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]
        vercel-project-id: [ 'prj_07Mk2x7ljSln8BpzcoI6pLkceac0' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
      - run: corepack enable
      - run: pnpm install && pnpm build && pnpm build:test
        working-directory: ${{ matrix.actions-directory }}
      - uses: ./
        with:
          project-id: ${{ matrix.vercel-project-id }}
          token: ${{ secrets.VERCEL_TOKEN }}
      - run: echo "${{ github.env.PRODUCTION }}  <- this should be hidden"